### ISSUE TITLE
bytes loss using rf22.recv() on Chistera

### ISSUE THREAD

**Issue by vandenbo** [Snootlab/lora_chisterapi#3]
Hello,

I have detected a problem with my RFM22b on the Chistera using lora_chisterapi as a receiver. 

- I send 10 bytes frames (0x00, 0x01, ... 0x09) with a TeensyWiNo using the code attached "rf22_test_sender".
- I use the Chistera as a receiver using the code attached "receiver.cpp".
- I use an other TeensyWiNo as a second receiver to compare received messages, using the code attached "receiver.ino".

With the TeensyWiNo receiver, frames are received correctly:

```
RF22	-20dBm	|00|01|02|03|04|05|06|07|08|09|
RF22	-20dBm	|00|01|02|03|04|05|06|07|08|09|
RF22	-20dBm	|00|01|02|03|04|05|06|07|08|09|
RF22	-20dBm	|00|01|02|03|04|05|06|07|08|09|
RF22	-20dBm	|00|01|02|03|04|05|06|07|08|09|
RF22	-20dBm	|00|01|02|03|04|05|06|07|08|09|
```

but on the Chistera, the frames are not correct:

```
RF22	-3dBm	|04|05|06|07|08|09|06|06|06|06|
RF22	-3dBm	|03|04|05|06|07|08|09|07|07|07|
RF22	-3dBm	|03|04|05|06|07|08|09|07|07|07|
RF22	-3dBm	|02|03|04|05|06|07|08|09|08|08|
RF22	-3dBm	|02|03|04|05|06|07|08|09|08|08|
RF22	-4dBm	|02|03|04|05|06|07|08|09|08|08|
```

I use:
- lora_chisterapi commit b4f9d6b8d0d4eeea67d331484cb59c9fc76b26c5
- gcc version 4.9.2 (Raspbian 4.9.2-10) 
- uname -r: 4.1.19+
[chistera.zip](https://github.com/Snootlab/lora_chisterapi/files/626871/chistera.zip)

**Comment by NICOLASGON** [comment]
Hello,

I did a test with the same setup and all worked fine ...

This is what i got on the chisterapi : 
RF22	-20dBm	|00|01|02|03|04|05|06|07|08|09|
RF22	-32dBm	|00|01|02|03|04|05|06|07|08|09|
RF22	-20dBm	|00|01|02|03|04|05|06|07|08|09|
RF22	-32dBm	|00|01|02|03|04|05|06|07|08|09|
RF22	-20dBm	|00|01|02|03|04|05|06|07|08|09|
RF22	-31dBm	|00|01|02|03|04|05|06|07|08|09|
RF22	-20dBm	|00|01|02|03|04|05|06|07|08|09|

You forgot to initialize Serial in your rf22_test_sender.ino but it's not the problem here.
Get me back your hardware to see if it's a Hardware Fault or not :)

**Comment by vandenbo** [comment]
This bug is reproducible on a Rasberry Pi model B+ V1.2 (2014) (aka the first version with 4 USB ports). On a Raspberry Pi 3 model B v1.2 (2015), all is OK. 

If I can, I will test the sketch on Raspberry Pi 2.
